### ISSUE TITLE
Getting this issue when I am launching PWECouponsActivity

### ISSUE THREAD

**Issue by PankajRaincan** [easebuzz/paywitheasebuzz-android-lib#1]
com.raincan.android.hybrid E/AndroidRuntime: FATAL EXCEPTION: main
                                             Process: com.raincan.android.hybrid, PID: 3995
                                             java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit/client/OkClient;
                                                 at java.lang.Class.newInstance(Native Method)
                                                 at android.app.Instrumentation.newActivity(Instrumentation.java:1100)
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2551)
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:154)
                                                 at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit.client.OkClient" on path: DexPathList[[zip file "/data/app/com.raincan.android.hybrid-1/base.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.raincan.android.hybrid-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.raincan.android.hybrid-1/lib/arm, /data/app/com.raincan.android.hybrid-1/base.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.raincan.android.hybrid-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                 at java.lang.Class.newInstance(Native Method) 
                                                 at android.app.Instrumentation.newActivity(Instrumentation.java:1100) 
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2551) 
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                 at android.os.Looper.loop(Looper.java:154) 
                                                 at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by RobinKumar5986** [comment]
This error message is a stack trace from an Android application that has encountered a java.lang.NoClassDefFoundError. This usually occurs when the runtime is trying to load a class at runtime, but it can't find the definition of the class.

In this specific case, the class that couldn't be found is retrofit.client.OkClient. This suggests that the application is trying to use the Retrofit library for making HTTP requests, but it can't find the OkClient class.

To resolve this issue, you can try the following steps:

Check Retrofit Dependency: Make sure that you have included the Retrofit library in your project's dependencies correctly. You may need to add or update the Retrofit dependency in your project's build.gradle file.

implementation 'com.squareup.retrofit2:retrofit:2.x.x'
