### ISSUE TITLE
Attempt to invoke virtual method 'android.app.Dialog helper.PWECustomComponentHelper.getPWELoader(android.content.Context, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by kalaiyarasiMobi** [easebuzz/paywitheasebuzz-android-lib#2]
**java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Dialog helper.PWECustomComponentHelper.getPWELoader(android.content.Context, java.lang.String)' on a null object reference
        at com.easebuzz.payment.kit.PWEDebitCardActivity.sendUserCancelRequest(PWEDebitCardActivity.java:1160)
        at com.easebuzz.payment.kit.PWEDebitCardActivity.access$1300(PWEDebitCardActivity.java:73)
        at com.easebuzz.payment.kit.PWEDebitCardActivity$9.onClick(PWEDebitCardActivity.java:1139)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:172)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)**

**Comment by kalaiyarasiMobi** [comment]
`private PWECustomComponentHelper pwe_custom_component_helper;`

pwe_custom_component_helper is not initialized
